### ISSUE TITLE
Not working on Cloudflare Workers...

### ISSUE THREAD

**Issue by t-botz** [launchdarkly/cloudflare-edge-sdk#13]
"edge-sdk" imply to me that you can run this lib on the edge, which means, no `node` dependencies...
When running on Cloudflare workers this lib fails to a fair amount of dependencies to `crypto` and `os`

**Comment by bwoskow-ld** [comment]
Hi @t-botz,

Thanks for trying out our Cloudflare SDK. Webpack should automatically load the polyfills necessary for the Node dependencies. Can you compare your configuration to [this template](https://github.com/launchdarkly/launchdarkly-cloudflare-worker-template)? See [our Cloudflare integration documentation](https://docs.launchdarkly.com/integrations/cloudflare) for more information.

More long term, we plan on updating our Cloudflare SDK to not have any transitive Node package dependencies. However, as this update isn't currently available, today we need to work around this problem with polyfills.

Cheers,
@bwoskow-ld

**Comment by dannyrb** [comment]
@bwoskow-ld, do you know if the worker template is compatible with the latest version of `wrangler`? The steps outlined here appear to be outdated:

- https://docs.launchdarkly.com/guides/infrastructure/cloudflare-workers

**Comment by bwoskow-ld** [comment]
Hi @dannyrb, my colleague @ldhenry responded to [your other issue](https://github.com/launchdarkly/cloudflare-edge-sdk/issues/15) regarding `wrangler` compatibility. Take a look at his response.

**Comment by t-botz** [comment]
Yes thanks, its working 🙂
