### ISSUE TITLE
Incorrect TypeScript module definition

### ISSUE THREAD

**Issue by dandean** [launchdarkly/cloudflare-edge-sdk#7]
**Describe the bug**

It appears that the type definitions for this module are incorrect. When I import this module I get the following message:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/18332/176831482-cc768a11-50ec-4cc5-9a67-d48ec8445a68.png">

If I open up the type definition file and remove `/client` from the end of the module declaration it works fine.

Before:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/18332/176831590-9f34a2cd-8b67-4974-9ed1-8816491dce28.png">

After:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/18332/176831618-d5394474-10cb-4357-8ea5-0d531a4f542c.png">

TypeScript's language server is now happy:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/18332/176831687-d125f7dd-7611-4f4a-a36e-7666d908357e.png">

**To reproduce**

See above.

**Expected behavior**

The module declaration matches the exported JavaScript source.

**SDK version**

^0.1.0

**Language version, developer tools**

Node 14.8.1

**Comment by XieX** [comment]
Thanks for reporting @dandean, fix is in the works 👍

**Comment by XieX** [comment]
@dandean This should be fixed in v0.1.1 - let me know if you still have problems, and thanks again for reporting the issue!

**Comment by dandean** [comment]
Thank you!
